### ISSUE TITLE
rsync: failed to set times on "/path/to/folder": Operation not permitted (1)

### ISSUE THREAD

**Issue by kyawmyintthein** [bom-d-van/harp#5]
When I deploy beego project on AWS. I got following error.
: rsync: failed to set times on "/ubuntu/go/src/hydrodesk-api/.": Operation not permitted (1)
rsync: recv_generator: mkdir "/ubuntu/go/src/hydrodesk-api/.git" failed: Permission denied (13)
**\* Skipping any contents from this failed directory ***
rsync: recv_generator: mkdir "/ubuntu/go/src/hydrodesk-api/.harp" failed: Permission denied (13)
**\* Skipping any contents from this failed directory ***
rsync: recv_generator: mkdir "/ubuntu/go/src/hydrodesk-api/Godeps" failed: Permission denied (13)
**\* Skipping any contents from this failed directory ***
rsync: recv_generator: mkdir "/ubuntu/go/src/hydrodesk-api/conf" failed: Permission denied (13)
**\* Skipping any contents from this failed directory ***
rsync: recv_generator: mkdir "/ubuntu/go/src/hydrodesk-api/controllers" failed: Permission denied (13)
**\* Skipping any contents from this failed directory ***
rsync: recv_generator: mkdir "/ubuntu/go/src/hydrodesk-api/db" failed: Permission denied (13)
**\* Skipping any contents from this failed directory ***
rsync: recv_generator: mkdir "/ubuntu/go/src/hydrodesk-api/deps" failed: Permission denied (13)
**\* Skipping any contents from this failed directory ***
rsync: recv_generator: mkdir "/ubuntu/go/src/hydrodesk-api/docs" failed: Permission denied (13)

**Comment by bom-d-van** [comment]
Hi @kyawmyintthein , could you post your harp.json file and harp version (`harp -v`) here too?
And it appears to be a permission bug. harp use rsync to upload the files, are you able to upload files to the server with rsync yourself? 
~~BTW, do you have a user `go` on the server or~~
Do you have write permission to `/ubuntu/go` on the server?

**Comment by kyawmyintthein** [comment]
Hi @bom-d-van,
 I fixed the problem. The problem is because of I added wrong GOPATH in harp.json. Thanks.
