### ISSUE TITLE
Is there any shared folder like capitrano in harp?

### ISSUE THREAD

**Issue by kyawmyintthein** [bom-d-van/harp#6]

**Comment by bom-d-van** [comment]
Hi @kyawmyintthein could you explain a little bit of what's your intention of using the shared folder?

**Comment by kyawmyintthein** [comment]
When I deploy, I think harp will upload the project folder to server. I have a config file which is used as project config such as database url, database name and etc. It was different for local, staging and production. My idea is I don't want to include that file in project folder. I just want to place manually in shared folder in server and load from it.

**Comment by bom-d-van** [comment]
@kyawmyintthein I see, thanks for your explanation.

There is neither shared folder concept nor built-in solution in `harp` for this problem. But there are many solutions to this common problem.

My own solution is that I use a script to copy my production configs into the project directory and then call `harp` for deployment, then remove it after that.

``` sh
cp /path/to/prod.json /path/to/project/config/prod.json

harp -s prod deploy

rm /path/to/project/config/prod.json
```

You can also place the config file on server and specify the path as environment variable in `harp.json` or [~/.pam_environment](https://help.ubuntu.com/community/EnvironmentVariables#A.2BAH4-.2F.pam_environment) if you are using Ubuntu:

```
"Servers": {
        "prod": [{
            "User": "app",
            "Envs": {
                "CONFIG": "/path/to/config.json"
            },
            "Host": "192.168.59.103",
            "Port": ":49155"
        }
    }
```

**Comment by kyawmyintthein** [comment]
Oh! great. thanks @bom-d-van

**Comment by bom-d-van** [comment]
I think you know this, but just in case, by the environment variable approach you need to tweak your app a bit to check for the config path. 
Hope harp could be a helpful tool to you and your team.
